// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-kF0iPDvkL7_VVoC4eQF9L-QCyEGiyDw',
    appId: '1:723840251214:web:d8fdb70e4479d03f735a1f',
    messagingSenderId: '723840251214',
    projectId: 'food-delivery-around-faculty',
    authDomain: 'food-delivery-around-faculty.firebaseapp.com',
    storageBucket: 'food-delivery-around-faculty.firebasestorage.app',
    measurementId: 'G-JEXYTK5BKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5_-Sbj_gy_kqPeYpnINWauGivif2D0xM',
    appId: '1:723840251214:android:7c2f55a30e8d8a85735a1f',
    messagingSenderId: '723840251214',
    projectId: 'food-delivery-around-faculty',
    storageBucket: 'food-delivery-around-faculty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC731wq9xO-PTchKo2ThbBkzZ3Li1xrvNo',
    appId: '1:723840251214:ios:951e1116a3bbb74b735a1f',
    messagingSenderId: '723840251214',
    projectId: 'food-delivery-around-faculty',
    storageBucket: 'food-delivery-around-faculty.firebasestorage.app',
    iosBundleId: 'com.example.eato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC731wq9xO-PTchKo2ThbBkzZ3Li1xrvNo',
    appId: '1:723840251214:ios:951e1116a3bbb74b735a1f',
    messagingSenderId: '723840251214',
    projectId: 'food-delivery-around-faculty',
    storageBucket: 'food-delivery-around-faculty.firebasestorage.app',
    iosBundleId: 'com.example.eato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-kF0iPDvkL7_VVoC4eQF9L-QCyEGiyDw',
    appId: '1:723840251214:web:1167dd66bf0c9a85735a1f',
    messagingSenderId: '723840251214',
    projectId: 'food-delivery-around-faculty',
    authDomain: 'food-delivery-around-faculty.firebaseapp.com',
    storageBucket: 'food-delivery-around-faculty.firebasestorage.app',
    measurementId: 'G-67YEE8QRZ9',
  );
}
